spring:
  application:
    name: two-factor-service
  datasource:
    url: "jdbc:mysql://localhost:3306/userservice?autoreconnect=true"
    password: "root"
    username: "root"

   dbcp2:
    test-while-idle: true
    test-on-borrow: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 30000
    validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver

  jta:
    atomikos:
      properties:
        max-actives: 15

  redis:
    jedis:
      pool:
        max-idle: 10
        max-wait: 8000
